name: 'Terraform Init'
description: 'terraform init commands'
inputs:
  aws_account_number:
    description: 'Account Number'
    required: true
    default: '339712836882'
  aws_role_name:
    description: 'Aws role with polices to deploy'
    required: true
    default: 'github-actions'
  aws_region: 
    description: 'Aws region'
    required: true
    default: 'us-east-1'
  terraform_state_file:
    description: 'State file Terraform'
    required: true
  terraform_bucket_name:
    description: 'Bucket Terraform'
    required: true
  terraform_directory:
    description: 'Directory containing Terraform files'
    required: false
    default: ''


runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print
      shell: bash
      run: |
        echo "Region: ${{ inputs.aws_region }}"

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_number }}:role/${{ inputs.aws_role_name }}
        role-session-name: ${{ inputs.aws_role_name }}
        aws-region: ${{ inputs.aws_region }}

    - name: Prepare Terraform plugin cache dir
      if: ${{ inputs.terraform_directory != '' }}
      working-directory: ${{ inputs.terraform_directory }}
      run: mkdir -p ~/.terraform.d/plugin-cache
      shell: bash

    - name: Prepare Terraform plugin cache dir root
      if: ${{ inputs.terraform_directory == '' }}
      working-directory: ${{ inputs.terraform_directory }}
      run: mkdir -p ~/.terraform.d/plugin-cache
      shell: bash

    - name: Cache Terraform providers & modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.terraform.d/plugin-cache
          terraform/.terraform
        key: ${{ runner.os }}-terraform-${{ hashFiles('terraform/terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-


    - name: Terraform Init
      if: ${{ inputs.terraform_directory != '' }}
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: terraform init -backend-config=bucket=${{ inputs.terraform_bucket_name }} -backend-config=key=${{ inputs.terraform_state_file }} -backend-config=region=us-east-1

    - name: Terraform Init
      if: ${{ inputs.terraform_directory == '' }} # Executa apenas se terraform_directory não estiver vazio
      shell: bash
      run: terraform init -backend-config=bucket=${{ inputs.terraform_bucket_name }} -backend-config=key=${{ inputs.terraform_state_file }} -backend-config=region=us-east-1
      
