name: 'Terraform plan'
description: 'terraform plan commands'
inputs:
  aws_account_number:
    description: 'Account Number'
    required: true
  aws_role_name:
    description: 'Aws role with polices to deploy'
    required: true
  aws_region:
    description: 'Aws region'
    required: true
  artifact_name:
    description: 'Artifact Name'
    required: true
    default: 'terraform'
  terraform_directory:
    description: 'Directory containing Terraform files'
    required: false
    default: ''

runs:
  using: composite
  steps:

  - name: Set up Node.js
    uses: actions/setup-node@v4
    with:
        node-version: '20'

  - uses: hashicorp/setup-terraform@v3
    name: setup
    with:
        terraform_version: "1.5.0"

  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::${{ inputs.aws_account_number }}:role/${{ inputs.aws_role_name }}
      role-session-name: ${{ inputs.aws_role_name }}
      aws-region: ${{ inputs.aws_region }}

  - name: Download Artifact
    if: ${{ inputs.artifact_name != '' }}
    uses: actions/download-artifact@v4
    with:
      name: ${{ inputs.artifact_name }}

  - name: Move files
    shell: bash
    run: mv loaded-content .terraform

  - name: Set permissions for Terraform providers
    shell: bash
    run: |
      chmod -R +x .

  - name: Terraform Plan
    shell: bash
    run: |
      terraform plan -no-color | tee terraform_plan.log

  - name: Terraform Plan
    shell: bash
    if: ${{ inputs.terraform_directory != '' }}
    run: |
      cd ${{ inputs.terraform_directory }}
      terraform plan -no-color | tee terraform_plan.log

  - name: Upload Terraform Plan Log
    if: failure()
    uses: actions/upload-artifact@v4
    with:
      name: terraform-plan-log
      path: terraform_plan.log