name: 'Terraform Apply'
description: 'terraform apply commands'
inputs:
  aws_account_number:
    description: 'Account Number'
    required: true
    default: '339712836882'
  aws_role_name:
    description: 'Aws role with polices to deploy'
    required: true
    default: 'github-actions'
  aws_region: 
    description: 'Aws region'
    required: true
    default: 'us-east-1'
  artifact_name:
    description: 'Artifact Name'
    required: true
    default: 'terraform'




runs:
  using: composite
  steps:

  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::${{ inputs.aws_account_number }}:role/${{ inputs.aws_role_name }}
      role-session-name: ${{ inputs.aws_role_name }}
      aws-region: ${{ inputs.aws_region }}

  - name: Set permissions for Terraform providers
    shell: bash
    run: chmod -R +x .

  - name: Terraform Apply
    shell: bash
    run: |
      terraform apply -auto-approve