name: 'Flyway converter'
description: 'Discord message webhook'
inputs:
  json_path:
    description: 'Json Flyway Path'
    required: false
  parameters:
    description: 'Parameters'
    required: false
runs:
  using: composite
  steps:

  - name: Configurar Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.x'

  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install requests

  - name: Checkout script repository
    uses: actions/checkout@v4
    with:
      repository: 'aksistech/actions'
      path: code

  - name: Convert
    shell: bash
    env:
      INPUT_PARAMETERS: "${{ inputs.parameters }}"
      JSON_PATH: "${{ inputs.json_path }}"
    run: python code/.github/scripts/convert-migration-to-fields-discord.py

