name: 'Golang Build'
description: 'Golang Build Applications'
inputs:
  go-version:
    description: 'go version'
    required: true
    default: '^1.19'

runs:
  using: composite
  steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Set up Go
    uses: actions/setup-go@v5
    with:
      go-version: ${{ inputs.go-version }}

  - name: Clean mod cache
    run: go clean --modcache
    shell: bash

  - name: Tidy
    shell: bash
    run: go mod tidy

  - name: Download dependencies
    shell: bash
    run: go mod download