name: 'Golang Build'
description: 'Golang Build Applications'
inputs:
  go-version:
    description: 'go version'
    required: true
    default: '^1.19'

runs:
  using: composite
  steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - uses: actions/cache@v4
    with:
      path: |
        ~/.cache/go-build
        ~/go/pkg/mod
      key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      restore-keys: |
        ${{ runner.os }}-go-

  - name: Set up Go
    uses: actions/setup-go@v5
    with:
      go-version: ${{ inputs.go-version }}

  - name: Tidy
    shell: bash
    run: go mod tidy

  - name: Download dependencies
    shell: bash
    run: go mod download