name: 'Terraform Plan'
description: 'terraform plan commands'
inputs:
  aws_account_number:
    description: 'Account Number'
    required: true
  aws_role_name:
    description: 'Aws role with polices to deploy'
    required: true
  aws_region:
    description: 'Aws region'
    required: true
  artifact_name:
    description: 'Artifact Name'
    required: true
    default: 'terraform'




runs:
  using: composite
  steps:

  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::${{ inputs.aws_account_number }}:role/${{ inputs.aws_role_name }}
      role-session-name: ${{ inputs.aws_role_name }}
      aws-region: ${{ inputs.aws_region }}

  - name: Terraform Apply
    shell: bash
    run: |
      cd terraform
      terraform plan