name: 'Terraform Plan'
description: 'terraform plan commands'
inputs:
  aws_account_number:
    description: 'Account Number'
    required: true
  aws_role_name:
    description: 'Aws role with polices to deploy'
    required: true
  aws_region:
    description: 'Aws region'
    required: true
  terraform_directory:
    description: 'Directory containing Terraform files'
    required: false
    default: ''
  vars:
    description: 'Terraform variables'
    required: false
    default: ''


runs:
  using: composite
  steps:

  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::${{ inputs.aws_account_number }}:role/${{ inputs.aws_role_name }}
      role-session-name: ${{ inputs.aws_role_name }}
      aws-region: ${{ inputs.aws_region }}


  - name: Terraform Plan (${{ inputs.terraform_directory != '' && inputs.vars == ''}})
    if: ${{ inputs.terraform_directory != '' && inputs.vars == ''}}
    working-directory: ${{ inputs.terraform_directory }}
    shell: bash
    run: terraform plan

  - name: Terraform Plan (${{ inputs.terraform_directory != '' && inputs.vars == ''}})
    if: ${{ inputs.terraform_directory == '' && inputs.vars == ''}}
    shell: bash
    run: terraform plan


  - name: Terraform Plan (${{ inputs.terraform_directory != '' && inputs.vars == ''}})
    if: ${{ inputs.terraform_directory != '' && inputs.vars != '' }}
    working-directory: ${{ inputs.terraform_directory }}
    shell: bash
    run: terraform plan -auto-approve -var-file=${{ inputs.vars }}

  - name: Terraform Plan (${{ inputs.terraform_directory != '' && inputs.vars == ''}})
    if: ${{ inputs.terraform_directory == '' && inputs.vars != '' }}
    shell: bash
    run: terraform plan -auto-approve -var-file=${{ inputs.vars }}
