name: 'Discord Notifier'
description: 'Discord message webhook'
inputs:
  title:
    description: 'Title'
    required: false
    default: 'Github Actions'
  description:
    description: 'Description'
    required: true
  severity:
    description: 'Severity INFO|WARN|ERROR'
    required: false
    default: 'INFO'
  webhook:
    description: 'Discord Webhook'
    required: true
  fields:
    description: 'Json Fields'
    required: true
    default: '[]'
runs:
  using: composite
  steps:

  - name: Configurar Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.x'

  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install requests

  - name: Checkout script repository
    uses: actions/checkout@v4
    with:
      repository: 'aksistech/actions'
      path: code

  - name: Send message
    shell: bash
    env:
      DISCORD_WEBHOOK_URL: "${{ inputs.webhook }}"
      TITLE: "${{ inputs.title }}"
      DESCRIPTION: "${{ inputs.description }}"
      FIELDS: "${{ inputs.fields }}"
      COLOR: "${{ inputs.severity }}"
      REPOSITORY_NAME: "${{ github.repository }}"
      WORKFLOW_NAME: "${{ github.workflow }}"
      GITHUB_REF_NAME: "${{ github.ref_name }}"
      WORKFLOW_BUILD: "${{ github.run_number }}"
    run: python code/.github/scripts/discord_notifier.py

