name: Terraform Plan

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      runner_name:
        required: true
        type: string
      runner_category:
        required: true
        type: string
      branch_name:
        required: true
        type: string
      aws_region:
        required: false
        type: string
        default: 'us-east-1'
      terraform_directory:
        required: false
        type: string
      values_file:
        required: true
        type: string
      terraform_state_file:
        required: false
        type: string
        default: 'terraform.tfstate'

jobs:
  terraform-apply:
    name: apply
    environment: ${{ github.ref_name }}
    runs-on: ['${{ inputs.runner_name }}', '${{inputs.branch_name}}', '${{inputs.runner_category}}', "self-hosted", "linux", "x64", "amazon"]
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '20'

    - uses: hashicorp/setup-terraform@v3
      name: setup
      with:
          terraform_version: "1.5.0"


    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_NUMBER_ENV }}:role/github-actions-${{ github.ref_name }}
        role-session-name: github-actions-${{ github.ref_name }}
        aws-region: 'us-east-1'

    - name: Prepare Terraform plugin cache dir
      run: mkdir -p ~/.terraform.d/plugin-cache

    - name: Cache Terraform providers & modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.terraform.d/plugin-cache
          terraform/.terraform
        key: ${{ runner.os }}-terraform-${{ hashFiles('terraform/terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Terraform Init
      working-directory: ${{ inputs.terraform_directory }}
      run: |
        terraform init -backend-config=bucket=${{ vars.TERRAFORM_BUCKET }} -backend-config=key=${{ github.event.repository.name }}/${{ inputs.terraform_state_file }} -backend-config=region=us-east-1


    - name: Download files
      uses: actions/download-artifact@v4
      with:
        name: terraform-vars
        path: ${{ inputs.terraform_directory }}


    - name: Check Has Changes
      id: terraform_plan_has_changes
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}
      run: |
        terraform apply -var-file=${{ inputs.values_file }} -auto-approve
